### ISSUE TITLE
Error: Most middleware software is no longer bundled and must be installed separately.

### ISSUE THREAD

**Issue by hamadyne** [jtangelder/denon-remote#2]
I'm trying to get the server software to run, but it won't start up at all. I tried installing Express and the middleware functions to no avail.

```
Error: Most middleware (like bodyParser) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
  at Function.Object.defineProperty.get (C:\Users\tyler.WORKGROUP\Documents\GitHub\denon-remote\node_modules\express\lib\express.js:99:13)
  at Object.<anonymous> (C:\Users\tyler.WORKGROUP\Documents\GitHub\denon-remote\server.coffee:13:16)
  at Object.<anonymous> (C:\Users\tyler.WORKGROUP\Documents\GitHub\denon-remote\server.coffee:2:1)

  at Module._compile (module.js:460:26)
  at Object.exports.run (C:\Users\tyler.WORKGROUP\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\coffee-script.js:134:23)
  at compileScript (C:\Users\tyler.WORKGROUP\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:224:29)
  at compilePath (C:\Users\tyler.WORKGROUP\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:174:14)
  at Object.exports.run (C:\Users\tyler.WORKGROUP\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:98:20)
  at Object.<anonymous> (C:\Users\tyler.WORKGROUP\AppData\Roaming\npm\node_modules\coffee-script\bin\coffee:7:41)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by jtangelder** [comment]
I see that in package.json doesn't contain versions for the dependencies. you can try setting them to older versions. a PR will be merged!

**Comment by hamadyne** [comment]
Solution: Install `body-parser` and include the following lines in server.coffee: 

`bodyParser = require ('body-parser')`

`app.use bodyParser.json()`

`app.use bodyParser.urlencoded(extended: true)`

**Comment by jtangelder** [comment]
I've just updated the repo and did a rewrite of the codebase. It now is a simple CLI..! I will close this issue, since it has become obsolete. 🙃
