### ISSUE TITLE
error after install

### ISSUE THREAD

**Issue by Hotte2017** [jtangelder/denon-remote#9]
HI!
After installing node-js legacy on a Mint17 machine i got these errors:
Did I miss something?

/usr/local/lib/node_modules/denon/lib/DenonClient.js:3
module.exports = class DenonClient {
                 ^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/denon/index.js:5:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by jtangelder** [comment]
Try updating the the latest version of node.

**Comment by Hotte2017** [comment]
Thank you! That helped.
Once I did a similar command-based remote in python, but with graph. interface (glade).
My goal was to replace the bad Denon app by an own remote on my Linux PC.
I stoped the project because i could not figure out how to send a part of a list like a radio station directly to the denon. Secondly when returning the display of the denon to my PC things become time-critical and it is very difficult to handle which characters/Information of the display are transferred.
Have you seen any other project for the AVR 1000 or similar?

**Comment by jtangelder** [comment]
Glad it solved the issue!
Didn't looked for other projects controlling the Denon AVRs, but I would
assume they all work with the same telnet commands if the software hasn't
changed too much.

Op di 16 mei 2017 om 20:15 schreef Hotte2017 <notifications@github.com>:
